### PR TITLE
Add ixgbe driver patch to support BCM54616S_E_PHY phy

### PR DESCRIPTION
**Pull request by jostar-yang**
Re-open this PR to checkin patch for ixgbe BCM54616S_E_PHY

### CODE REVIEW

**Comment by jostar-yang** [comment]
This PR is patch for IXGBE. 
0011-support-Broadcom-54616-Phy-for-Intel-igb-driver.patch is for IGB.
They are different code.

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
i am ok with patch, but can you format the patch correctly? using the checkpatch.pl

**Comment by jostar-yang** [comment]
OK. I will check to use checkpatch.pl.

**Comment by jostar-yang** [comment]
I do checkpatch.pl to check this patch format. After correct format to the patch, I resend new PR #122.

**Pull request closed without merging**
