### PR TITLE
Ported hwmon: (pmbus_core) Check adapter PEC support patch to 5.10.40 kernel

### PR DESCRIPTION
**Pull request by msiddare**
Ported hwmon: (pmbus_core) Check adapter PEC support patch to 5.10.40 kernel.

When switch from Linux 4.19.x to 5.10.40 the patch was disabled, as it did not apply cleanly. Forward port it to Linux 5.10.40 and add it to the Linux 5.10 patch series.

Test on cisco-8000 platform
root@localhost:/home/cisco# show plat temp
Sensor Temperature High TH Low TH Crit High TH Crit Low TH Warning Timestamp
CPU_U17_P1P05V_TEMP 35.187 125 -5 135 -10 False 20211011 13:57:45
CPU_U17_PVCCIN_TEMP 34.937 125 -5 135 -10 False 20211011 13:57:45
CPU_U117_P1P2V_TEMP 30.75 125 -5 135 -10 False 20211011 13:57:46
CPU_U117_P1P05V_TEMP 31 125 -5 135 -10 False 20211011 13:57:46
DIMM_TEMP1 28.25 125 -5 135 -10 False 20211011 13:57:47
FAN_Sensor 32.375 97 -5 102 -10 False 20211011 13:57:45
MB_3_3V_L_TEMP_L1 33.187 125 -5 135 -10 False 20211011 13:57:47
MB_3_3V_L_TEMP_L2 33.187 125 -5 135 -10 False 20211011 13:57:47
MB_3_3V_R_VDDCK_TEMP_L1 34.187 125 -5 135 -10 False 20211011 13:57:46
MB_3_3V_R_VDDCK_TEMP_L2 48.312 125 -5 135 -10 False 20211011 13:57:46
MB_GB_CORE_TEMP_L1 43.312 110 -5 115 -10 False 20211011 13:57:47
MB_PORT_Sensor 22.563 120 -5 125 -10 False 20211011 13:57:45
MB_TMP421_Local 25 120 -5 125 -10 False 20211011 13:57:45
MB_VDDS_VDDA_TEMP_L1 48.125 125 -5 135 -10 False 20211011 13:57:46
MB_VDDS_VDDA_TEMP_L2 50.562 125 -5 135 -10 False 20211011 13:57:46
PSU0 HSNK_Temp1 28.75 91 -5 96 -10 False 20211011 13:57:47
PSU0 HSNK_Temp2 28.25 110 -5 115 -10 False 20211011 13:57:47
PSU0 Inlet_Temp 27.5 80 -5 85 -10 False 20211011 13:57:47
PSU0 Outlet_Temp 31.75 108 -5 110 -10 False 20211011 13:57:47
PSU1 HSNK_Temp1 29 91 -5 96 -10 False 20211011 13:57:47
PSU1 HSNK_Temp2 28.25 110 -5 115 -10 False 20211011 13:57:47
PSU1 Inlet_Temp 26.5 80 -5 85 -10 False 20211011 13:57:47
PSU1 Outlet_Temp 30.75 108 -5 110 -10 False 20211011 13:57:47
SSD_Temp 25 80 -5 85 -10 False 20211011 13:57:47
X86_CORE_0_T 37 125 -5 135 -10 False 20211011 13:57:45
X86_CORE_1_T 38 125 -5 135 -10 False 20211011 13:57:45
X86_CORE_2_T 37 125 -5 135 -10 False 20211011 13:57:45
X86_CORE_3_T 37 125 -5 135 -10 False 20211011 13:57:45
X86_PKG_TEMP 38 125 -5 135 -10 False 20211011 13:57:45
root@localhost:/home/cisco#

Signed-off-by: Madhava Reddy Siddareddygari <msiddare@cisco.com>

### CODE REVIEW

**Comment by paulmenzel** [comment]
Please follow [*How to Write a Git Commit Message*](https://chris.beams.io/posts/git-commit/) and improve *Ported patch to 5.10.40 kernel* (imperative mood, and say what patch).

> When switch from Linux 4.19.x to 5.10.40 the patch was disabled, as it did not apply cleanly. Forward port it to Linux 5.10.40 and add it to the Linux 5.10 patch series. Tested on ….

PS: How is the upstreaming effort of Cisco patches going?

**Comment by madhava28** [comment]
Ported hwmon: (pmbus_core) Check adapter PEC support patch to 5.10.40 kernel.

When switch from Linux 4.19.x to 5.10.40 the patch was disabled, as it did not apply cleanly. Forward port it to Linux 5.10.40 and add it to the Linux 5.10 patch series.

**Comment by sachinv-msft** [comment]
@saiarcot895 fyi

**Comment by paulmenzel** [comment]
In the merge/pull request description, please mark up the text using (GitHub) Markdown. You can either indent the terminal paste by four spaces, or enclose them in \`\`\`/\`\`\`.

**Comment by paulmenzel** [comment]
Please note in the patch file, that this patch was applied to Linux 5.14 in [commit 4e5418f787 (hwmon: (pmbus_core) Check adapter PEC support)](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=4e5418f787ec56d7fe3c6efee486b8f508c58baf).

**Comment by paulmenzel** [comment]
The summary *Review comments incorporated to add kernel support for patch* is too unspecific. Please amend it. Maybe:

> cisco-hwmon-pmbus_core-pec-support-check: Document upstream Linux 5.14 inclusion

Also add *cisco-hwmon-pmbus_core-pec-support-check* to the commit message summary of the first patch.

PS: Please make sure, that reading `git log --oneline` gives already a good picture, on what is happening in the commits.

**Pull request merged**
