### PR TITLE
[Mellanox] Remove incorrectly generated patch allegedly avoiding kernel deadlock but causes one

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
Please cherry-pick this commit to 202012 and 202106.

Patch 0028-thermal-Fix-deadlock-in-thermal-thermal_zone_device_.patch was incorrectly generated. It is supposed to backport Linux commit [torvalds/linux@163b00c](https://github.com/torvalds/linux/commit/163b00c), but the commit was already backported to the stable series in v4.19.89, so included in Linux v.19.152 currently used by SONiC. Instead, the incorrect patch reverts the first hunk of the commit. So, remove it.

For the old patch, guess there was some mistake has been made while generating the patch. Instead of applying the fix to the code, it's generated in a opposite way, the content of the wrong patch is reverting the first part of the patch, so it can still building but make the fix incomplete.

Regression tests have been performed against these patches on the Mellanox platform, no issue found.

### CODE REVIEW

**Comment by paulmenzel** [comment]
Nit:

> regression tests have been performed against these patches on the Mellanox platform, no issue found

Please make that a sentence, starting with a capital letter, and adding a dot/period at the end.

Please mention, that the patch was added to Linux 5.5, and the LTS series it was added to are 5.4.3 and 4.19.89). SONiC’s Linux kernel is currently based on 4.19.152.

Also, it’s unclear to me, why the build bot (CI) succeeded.

**Comment by Junchao-Mellanox** [comment]
The CI build passed because the old patch is incorrect. Before applying the old patch, the fix is already in thermal_core.c; after applying the old patch, the fix is removed from thermal_core.c.

**Comment by Junchao-Mellanox** [comment]
@paulmenzel could you please review this again?

**Comment by paulmenzel** [comment]
> The CI build passed because the old patch is incorrect. Before applying the old patch, the fix is already in thermal_core.c; after applying the old patch, the fix is removed from thermal_core.c.

Excuse my ignorance. I do not understand. The old actually reverts the correct patch?

I screwed up my suggested sentence:

> The patch was added to Linux 5.5, and the LTS series it was added to are 5.4.3 and 4.19.89). SONiC’s Linux kernel is currently based on 4.19.152.

The patch was added to Linux 5.5, and the LTS series in 4.19.89 and 5.4.3. …

**Comment by Junchao-Mellanox** [comment]
Hi @paulmenzel , the old patch is wrong, it reverts or breaks the correct code.

Here is the correct patch content: https://github.com/torvalds/linux/commit/163b00c , you can compare it with sonic kernel code, it is already there, we don't need any patch, so i created this PR to remove the old one.

**Comment by Junchao-Mellanox** [comment]
@paulmenzel could you please review this again?

**Comment by qiluo-msft** [comment]
I am confused by below statement

> Here is the correct patch content: https://github.com/torvalds/linux/commit/163b00c , you can compare it with sonic kernel code or early 4.19 code here https://github.com/torvalds/linux/blob/v4.19/drivers/thermal/thermal_core.c

Checking the 4.19 code, it already contains the first part of the patch
```
cancel_delayed_work(&tz->poll_queue);
```

But it does not contains the second part of the patch
```
cancel_delayed_work_sync(&tz->poll_queue);
```

And I also has the same worry, if a patch does not work as expected, why build pass? This is not to blame you, but trying to understand what is missing in the patching process.

**Comment by Junchao-Mellanox** [comment]
Hi @qiluo-msft , 

> I am confused by below statement
> 
> > Here is the correct patch content: [torvalds/linux@163b00c](https://github.com/torvalds/linux/commit/163b00c) , you can compare it with sonic kernel code or early 4.19 code here https://github.com/torvalds/linux/blob/v4.19/drivers/thermal/thermal_core.c
> 
> Checking the 4.19 code, it already contains the first part of the patch
> 
> ```
> cancel_delayed_work(&tz->poll_queue);
> ```
> 
> But it does not contains the second part of the patch
> 
> ```
> cancel_delayed_work_sync(&tz->poll_queue);
> ```
> 

For this issue, it is strange. It seems 4.19 source code I provided before only have part of the patch content, but I checked the code in 4.19.152, the patch content is fully contained, please check https://github.com/torvalds/linux/blob/ad326970d25cc85128cd22d62398751ad072efff/drivers/thermal/thermal_core.c. And here is 4.19.152 commit: https://github.com/torvalds/linux/commit/ad326970d25cc85128cd22d62398751ad072efff. 

> And I also has the same worry, if a patch does not work as expected, why build pass? This is not to blame you, but trying to understand what is missing in the patching process.

For this issue, guess there was some mistake has been made while generating the patch. Instead of applying the fix to the code, it's generated in a opposite way, the content of the wrong patch is reverting the first part of the patch, so it can still building but make the fix incomplete.

**Review by qiluo-msft — APPROVED** [review]

**Comment by qiluo-msft** [comment]
@Junchao-Mellanox How about 201911 and earlier branches? Do we need to backport a patch?

**Comment by Junchao-Mellanox** [comment]
We don't need this in 201911, I checked the kernel source code in 201911, it is fine.

**Comment by paulmenzel** [comment]
Thank you for the analysis. Please update the merge/pull request description, and also amend the git commit message, and add a body.

**Comment by Junchao-Mellanox** [comment]
Fixed PR description and commit message, please check. @paulmenzel

**Comment by paulmenzel** [comment]
Thanks. Maybe use:

> [Mellanox] Remove incorrectly generated patch allegedly avoiding kernel deadlock
> 
> Patch `0028-thermal-Fix-deadlock-in-thermal-thermal_zone_device_.patch` was incorrectly generated. It is supposed to backport Linux commit torvalds/linux@163b00c, but the commit was already backported to the stable series in v4.19.89, so included in Linux v.19.152 currently used by SONiC. Instead, the incorrect patch reverts the first hunk of the commit. So, remove it.

Regression tests have been performed against these patches on the Mellanox platform, no issue found.

**Comment by paulmenzel** [comment]
[Mellanox] Remove incorrectly generated patch allegedly avoiding kernel deadlock → [Mellanox] Remove incorrectly generated patch allegedly avoiding kernel deadlock but causes one

**Comment by Junchao-Mellanox** [comment]
Fixed, please check.

**Comment by keboliu** [comment]
@lguohan @qiluo-msft would you please merge this one?

**Comment by qiluo-msft** [comment]
@lguohan Could you help review?

**Review by paulmenzel — APPROVED** [review]
The second paragraph in the merge/pull request description could be removed as the information is already included in the first one. But more information does not hurt, so it can be submitted/merged.

**Comment by qiluo-msft** [comment]
This patch is not existing on 202012 branch. Please double check.

**Comment by keboliu** [comment]
> This patch is not existing on 202012 branch. Please double check.

seems Guohan already cherry-picked to 202012? 816de4f551d39d595910e265144b7140f552c628

**Pull request merged**
