### PR TITLE
[Mellanox] [201911] backport kernel patches for hw-management 7.0100.2303

### PR DESCRIPTION
**Pull request by Junchao-Mellanox**
Backport patches:

0071-platform-x86-mlx-platform-Remove-PSU-EEPROM-configur.patch https://github.com/torvalds/linux/commit/c071afcea6ecf24a3c119f25ce9f71ffd55b5dc2
0072-thermal-Fix-deadlock-in-thermal-thermal_zone_device_.patch  https://github.com/torvalds/linux/commit/163b00cde7cf2206e248789d2780121ad5e6a70b
0073-mlxsw-core-Fix-memory-leak-on-module-removal.patch https://github.com/torvalds/linux/commit/adc80b6cfedff6dad8b93d46a5ea2775fd5af9ec
0074-platform-x86-mlx-platform-Remove-PSU-EEPROM-configur.patch https://github.com/torvalds/linux/commit/2bf5046bdb649908df8bcc0a012c56eee931a9af
0075-platform-x86-mlx-platform-Remove-PSU-EEPROM-configur.patch https://github.com/torvalds/linux/commit/912b341585e302ee44fc5a2733f7bcf505e2c86f
0076-hwmon-pmbus-Add-support-for-MPS-Multi-phase-mp2975-c.patch https://github.com/torvalds/linux/commit/2c6fcbb211494f1ff6ef384776944b9e04f4c14c

Re-numbering patches:
0077-mlxsw-core-Increase-critical-threshold-for-ASIC-ther.patch
0078-mlxsw-core-Add-validation-of-transceiver-temperature.patch
0079-mlxsw-core-Remove-critical-trip-point-from-thermal-z.patch

regression tests have been performed against these patches on the Mellanox platform, no issue found.

### CODE REVIEW

**Comment by lguohan** [comment]
why is 0072 is needed? i thought we have disabled thermal zone on this branch?

**Comment by lguohan** [comment]
0076 is a new feature, why do we need it on 201911 branch?

**Comment by Junchao-Mellanox** [comment]
> why is 0072 is needed? i thought we have disabled thermal zone on this branch?

In order to use kernel thermal control algorithm, thermalctld will enable thermal zone when it starts.

**Comment by keboliu** [comment]
> 0076 is a new feature, why do we need it on 201911 branch?

Hi Guohan, this new sensor support is required by the MSN4700 A1 system, we also planned to support it in 201911.

**Comment by keboliu** [comment]
> > why is 0072 is needed? i thought we have disabled thermal zone on this branch?
> 
> In order to use kernel thermal control algorithm, thermalctld will enable thermal zone when it starts.

added on top of Junchao's feedback:  it is NOT that the thermal zone is altogether disabled, what was disabled is the critical trip points to avoid the shutting down of zones by the thermal zone mechanism ,  but beside that the mechanism is still there and provides indications, such as warnings of changing temperatures etc. this patch is a common fix for the thermal zone  mechanism,  so it still valuable to backport it.

**Pull request merged**
