### PR TITLE
[patch/series]: Added a kernel patch to check csum_complete_sw in skb…

### PR DESCRIPTION
**Pull request by praveen-li**
…_copy_and_csum_datagram_msg.

Signed-off-by: Praveen Chaudhary<pchaudhary@linkedin.com>

The patch contains detailed description. Thanks a lot.

### CODE REVIEW

**Comment by praveen-li** [comment]
@lguohan and @zhenggen-xu : Kindly review. Thanks a lot.

**Comment by lguohan** [comment]
@praveen, can you fix the build failure?

**Comment by praveen-li** [comment]
> @praveen, can you fix the build failure?
@lguohan I will discard this PR, I notice that fix is already present in 4.9.168 but was not present in 4.9.110

**Comment by praveen-li** [comment]
Closing, since the fix is present in 4.9.168.

**Pull request closed without merging**
