### PR TITLE
buster

### PR DESCRIPTION
**Pull request by lguohan**
Signed-off-by: Guohan Lu <gulv@microsoft.com>

### CODE REVIEW

**Comment by lguohan** [comment]
@antony-rheneus, i ma having some issue to build arm kernel on 4.19. It seems something changed in the debian packaging. as you can see I commented the arm build line in the Makefile. Can you take a look at it?

**Comment by antony-rheneus** [comment]
> @antony-rheneus, i ma having some issue to build arm kernel on 4.19. It seems something changed in the debian packaging. as you can see I commented the arm build line in the Makefile. Can you take a look at it?

Ok sure.

**Comment by antony-rheneus** [comment]
> > @antony-rheneus, i ma having some issue to build arm kernel on 4.19. It seems something changed in the debian packaging. as you can see I commented the arm build line in the Makefile. Can you take a look at it?
> 
> Ok sure.


Overriding DEB_HOST_ARCH= to the target architecture, resolves the debian dh make. 

**```
diff --git a/Makefile b/Makefile
@@ -74,13 +74,13 @@ $(addprefix $(DEST)/, $(MAIN_TARGET)): $(DEST)/% :
        debian/bin/gencontrol.py

        # generate linux build file for amd64_none_amd64
-       # fakeroot make -f debian/rules.gen setup_armhf_none_armmp
-       # fakeroot make -f debian/rules.gen setup_arm64_none
-       fakeroot make -f debian/rules.gen setup_amd64_none_amd64
+       fakeroot make -f debian/rules.gen DEB_HOST_ARCH=armhf setup_armhf_none_armmp
+       fakeroot make -f debian/rules.gen DEB_HOST_ARCH=arm64 setup_arm64_none
+       fakeroot make -f debian/rules.gen DEB_HOST_ARCH=amd64 setup_amd64_none_amd64

        # Applying patches and configuration changes
-       # git add debian/build/build_armhf_none_armmp/.config -f
-       # git add debian/build/build_arm64_none_arm64/.config -f
+       git add debian/build/build_armhf_none_armmp/.config -f
+       git add debian/build/build_arm64_none_arm64/.config -f
        git add debian/build/build_amd64_none_amd64/.config -f
```**

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Comment by lguohan** [comment]
retest this please

**Pull request merged**
