### PR TITLE
[kconfig] [ARMHF] [marvell armada cpu support]

### PR DESCRIPTION
**Pull request by antony-rheneus**
Deleted Arm related unused patches
kconfig_inclusions:
  Enable Optoe
  Gpio based I2c Mux
  flash mtd parts support for flash partitions
kconfig_exclusions:
    Removed uncommon soc support to reduce kernel size
    Removed sound card
    Reoved debug slab

Signed-off-by: Antony Rheneus <arheneus@marvell.com>

### CODE REVIEW

**Comment by paulmenzel** [comment]
Please splite this up into one commit per list item in the merge/pull request description, and describe in the commit message, why that’s needed/useful.

**Comment by antony-rheneus** [comment]
> Please splite this up into one commit per list item in the merge/pull request description, and describe in the commit message, why that’s needed/useful.

@paulmenzel, Do you want each Kernel config should be raised as a separate PRs?

**Comment by paulmenzel** [comment]
> > Please splite this up into one commit per list item in the merge/pull request description, and describe in the commit message, why that’s needed/useful.
> 
> @paulmenzel, Do you want each Kernel config should be raised as a separate PRs?

No, not for me. But [one commit per change with a commit message](https://chris.beams.io/posts/git-commit/) would be nice.

**Comment by antony-rheneus** [comment]
> > > Please splite this up into one commit per list item in the merge/pull request description, and describe in the commit message, why that’s needed/useful.
> > 
> > 
> > @paulmenzel, Do you want each Kernel config should be raised as a separate PRs?
> 
> No, not for me. But [one commit per change with a commit message](https://chris.beams.io/posts/git-commit/) would be nice.

Added commits as per your request,

**Comment by paulmenzel** [comment]
Thank you for splitting this up. Please use `git rebase` to get rid of the first two commits, as the revert isn’t needed for review or the history.

Additionally, are you sure you do not break existing devices with these config changes? Keep in mind, the same Linux kernel image is used for all devices.

Lastly, for review and understanding your changes, commit messages are really necessary to explain the motivation and change. I believe the link I added in my first comment explains this well.

For example, the two commits:

1.  [use gzip compression for uboot extraction](https://github.com/Azure/sonic-linux-kernel/pull/172/commits/effedb4b9ec309f1254eac51a796c92ede879208)
2.  [kernel binary in gzipped for uboot to extract](https://github.com/Azure/sonic-linux-kernel/pull/172/commits/a48af47b8bfec40e2fc34c10e820f8fe4064def2)

It reads like they try to achive the same goal.

But, what is the current default, and what is the problem when loading the Linux kernel from U-Boot (what version)? Shouldn’t XZ be used, because the Linux kernel is smaller, and loading a smaller image is better than the added decompression time? Why Gzip? Big distributions moved to LZ4 or Zstd because that give the fastest loading speed. Without documenting your goal and reasoning, nobody knows why these changes are done.

**Comment by antony-rheneus** [comment]
> Thank you for splitting this up. Please use `git rebase` to get rid of the first two commits, as the revert isn’t needed for review or the history.
> 
> Additionally, are you sure you do not break existing devices with these config changes? Keep in mind, the same Linux kernel image is used for all devices.
> 
> Lastly, for review and understanding your changes, commit messages are really necessary to explain the motivation and change. I believe the link I added in my first comment explains this well.
> 
> For example, the two commits:
> 
> 1. [use gzip compression for uboot extraction](https://github.com/Azure/sonic-linux-kernel/pull/172/commits/effedb4b9ec309f1254eac51a796c92ede879208)
> 2. [kernel binary in gzipped for uboot to extract](https://github.com/Azure/sonic-linux-kernel/pull/172/commits/a48af47b8bfec40e2fc34c10e820f8fe4064def2)
> 
> It reads like they try to achive the same goal.
> 
> But, what is the current default, and what is the problem when loading the Linux kernel from U-Boot (what version)? Shouldn’t XZ be used, because the Linux kernel is smaller, and loading a smaller image is better than the added decompression time? Why Gzip? Big distributions moved to LZ4 or Zstd because that give the fastest loading speed. Without documenting your goal and reasoning, nobody knows why these changes are done.

Default Uboot config has gzip enabled and not xz, hence it is used.

**Comment by paulmenzel** [comment]
> Default Uboot config has gzip enabled and not xz, hence it is used.

Please amend the commit message, and add that information there. There are already U-Boot using devices supported, aren’t there. So why have they not run into this problem?

Also, there are x86 devices using GRUB which supports all compression methods. So why not change the U-Boot configuration, so that the optimal compression method can be used.

Lastly, why two commits, and why does `KERNEL_XZ` need to be *excluded*, if `KERNEL_GZIP` is included. The inclusion should be enough, shouldn’t it? If not, why?

**Comment by antony-rheneus** [comment]
> > Default Uboot config has gzip enabled and not xz, hence it is used.
> 
> Please amend the commit message, and add that information there. There are already U-Boot using devices supported, aren’t there. So why have they not run into this problem?
> 
> Also, there are x86 devices using GRUB which supports all compression methods. So why not change the U-Boot configuration, so that the optimal compression method can be used.
> 
> Lastly, why two commits, and why does `KERNEL_XZ` need to be _excluded_, if `KERNEL_GZIP` is included. The inclusion should be enough, shouldn’t it? If not, why?

There were no armhf platforms other than Marvell and Nokia.
Unlike Grub which is common across all platforms, Uboot is board specific and customized per platform. We can use uboot which came from soc and odm team, where it would be tested with specific uboot version.

Lastly, all kernel configs would be configured once and we do test the kernel. For your ease of review process I added per commits per config.

**Comment by lguohan** [comment]
i second @paulmenzel, let's say in the future we have a new arm platform that needs XZ and we decide to remove that exclusion. does it break your platform? Based on the conversation above, it make senes to use xz instead of gzip.

**Comment by lguohan** [comment]
i also share concerns as @paulmenzel , for all the exclusion, it is unclear if they are just desirable or they are must. The main concern is that in the future if we add new arm platform and needs to remove one of the exclusion, we have little knowledge to know whether it will break your platform or not.

**Comment by antony-rheneus** [comment]
> i second @paulmenzel, let's say in the future we have a new arm platform that needs XZ and we decide to remove that exclusion. does it break your platform? Based on the conversation above, it make senes to use xz instead of gzip.

new or old release uboot, gzip is available as default config in uboot. whereas for xz there is a possibility it may be present for old releases.

**Comment by antony-rheneus** [comment]
> i also share concerns as @paulmenzel , for all the exclusion, it is unclear if they are just desirable or they are must. The main concern is that in the future if we add new arm platform and needs to remove one of the exclusion, we have little knowledge to know whether it will break your platform or not.

Then the infra has to be changed to add/exclude kernel config from platform specific path, instead of common configuration file.

**Comment by lguohan** [comment]
we could have another platform based on armhf cpu, right? I assume armhf is not marvell specific.

**Comment by antony-rheneus** [comment]
> we could have another platform based on armhf cpu, right? I assume armhf is not marvell specific.

Yes, under armhf, there are various soc from different vendors.

**Comment by antony-rheneus** [comment]
> > we could have another platform based on armhf cpu, right? I assume armhf is not marvell specific.
> 
> Yes, under armhf, there are various soc from different vendors.

@lguohan , Would you please suggest? waiting for your feedback.

**Comment by antony-rheneus** [comment]
@lguohan, @paulmenzel , please review the changes which is based on platform soc

**Comment by paulmenzel** [comment]
Thank you for the updates, but I am sorry, I am still not able to review this properly. The summary of the whole merge/pull request should be updated with goal, often the commits are missing the reason, so nobody knows, why that change is done, and some of the earlier comments were still not addressed.

For example, the whole series should be rebased to be easily reviewable, and to be able to have a booting platform with each commit. That means, for example, that commit *Separate out SOC specific configuration based on platform architecture* should be first in the series and only change the scripts.

Lastly, there are also typos in the commit message summaries. For example *unsed* → *unused*.

**Comment by antony-rheneus** [comment]
> Thank you for the updates, but I am sorry, I am still not able to review this properly. The summary of the whole merge/pull request should be updated with goal, often the commits are missing the reason, so nobody knows, why that change is done, and some of the earlier comments were still not addressed.
> 
> For example, the whole series should be rebased to be easily reviewable, and to be able to have a booting platform with each commit. That means, for example, that commit _Separate out SOC specific configuration based on platform architecture_ should be first in the series and only change the scripts.
> 
> Lastly, there are also typos in the commit message summaries. For example _unsed_ → _unused_.

@paulmenzel , I have rebased. Let me know if it is now easily reviewable?

**Comment by lguohan** [comment]
in my opinion, the comment added for each commit is not really helpful. The comment needs explain the reason why, not what. People can look at the commit and understand what you did, but it is hard for people to figure out why. that is basically @paulmenzel 's point. I do not think rebase address his concern.

**Comment by antony-rheneus** [comment]
> in my opinion, the comment added for each commit is not really helpful. The comment needs explain the reason why, not what. People can look at the commit and understand what you did, but it is hard for people to figure out why. that is basically @paulmenzel 's point. I do not think rebase address his concern.

I have opened a new PR 176, please review it. As I could not rebase muliple times over this PR, as it doubled the commits from 24 to 48 and ended up in conflicts for each commit.
https://github.com/Azure/sonic-linux-kernel/pull/176

**Comment by antony-rheneus** [comment]
If you agree on review the PR 176, I will close  this PR 172.

**Comment by paulmenzel** [comment]
(You could have force pushed the rebased/new branch into this branch.)

The commits do *not* double when rebasing. What command did you use for rebasing? Maybe we can help you.

https://github.com/Azure/sonic-linux-kernel/pull/176 is definitely an improvement. Thank you for the work. But it’s still lacking the git commit message summaries. Please read [How to Write a Git Commit Message](https://chris.beams.io/posts/git-commit/) again. If there are open questions, please tell us. I’d really prefer to keep the discussion in this merge/pull request. But if you prefer https://github.com/Azure/sonic-linux-kernel/pull/176, then we can move there too.

**Comment by antony-rheneus** [comment]
> in my opinion, the comment added for each commit is not really helpful. The comment needs explain the reason why, not what. People can look at the commit and understand what you did, but it is hard for people to figure out why. that is basically @paulmenzel 's point. I do not think rebase address his concern.



> (You could have force pushed the rebased/new branch into this branch.)
> 
> The commits do _not_ double when rebasing. What command did you use for rebasing? Maybe we can help you.
> 
> #176 is definitely an improvement. Thank you for the work. But it’s still lacking the git commit message summaries. Please read [How to Write a Git Commit Message](https://chris.beams.io/posts/git-commit/) again. If there are open questions, please tell us. I’d really prefer to keep the discussion in this merge/pull request. But if you prefer #176, then we can move there too.

I used "git rebase --interactive HEAD~24", as totally I had 24 commits for each config.
If I were writing a feature, I could write a better summary or description. However Im just tapping out the existing config as per the default configuration required for a CPU Arch. 

Basically the config present in "arch/arm/configs/mvebu_v7_defconfig" should get into marvell-armhf configuration. Which is not so when debian build generates, hence I had to port configs from the mvebu_v7_defconfig, else kernel would not boot at all.

Another example I can refer, OPTOE driver, which I want to enable or disable, I can only brief enabling OPTOE  driver for SFF optics, rest woudl be just non-terse explanation from the OPTOE feature.

Better quote comment for my each commit description for what explanation you want to know specific to Armada A385 soc, so that I can get more or better explanation from soc team to add it.

**Comment by antony-rheneus** [comment]
@paulmenzel 

Command used for git reabse:-
`git rebase --interactive HEAD~24`

Git log of 46 commits:-
`$ git logline -n 46
* 8c21154 - (HEAD -> arm_update_master) Separate out SOC specific configuration based on platform architecture (7 hours ago) <Antony Rheneus>
* f5272b5 - no debug slab (7 hours ago) <Antony Rheneus>
* 0b57a01 - uefi based kernel module load security (7 hours ago) <Antony Rheneus>
* 3f87c83 - remove unsed sensor and sound card (7 hours ago) <Antony Rheneus>
* ae9b060 - no ntp external PPS needed (7 hours ago) <Antony Rheneus>
* 2b5c141 - removed unsed old 3com as limited memory is available to load kernelfrom uboot (7 hours ago) <Antony Rheneus>
* 06d94bf - no qemu firmware needed (7 hours ago) <Antony Rheneus>
* 40ab251 - EFI is not used (7 hours ago) <Antony Rheneus>
* f884729 - timer is set 100Hz (7 hours ago) <Antony Rheneus>
* ef68190 - removed unsed arch as limited memory is available to load kernelfrom uboot (7 hours ago) <Antony Rheneus>
* 43cb516 - removed unsed arch as limited memory is available to load kernelfrom uboot (7 hours ago) <Antony Rheneus>
* d3957aa - slab allocator is used (7 hours ago) <Antony Rheneus>
* fe5940f - tickless idle system (7 hours ago) <Antony Rheneus>
* cf9735d - use gzip compression for uboot extraction (7 hours ago) <Antony Rheneus>
* b2e4d9f - MTD parts for flash partition layout (7 hours ago) <Antony Rheneus>
* f827261 - peripheral drm quirks, usb support, ioport map (7 hours ago) <Antony Rheneus>
* 1e5f6b3 - Enable gpio i2c mux, opte and sff eeprom module (7 hours ago) <Antony Rheneus>
* 5df7918 - timer to 100Hz (7 hours ago) <Antony Rheneus>
* 926bb26 - default gpio pins to 0 (7 hours ago) <Antony Rheneus>
* 349d089 - regular slab allocator (7 hours ago) <Antony Rheneus>
* 4f0bbe4 - Disable heap randomization (7 hours ago) <Antony Rheneus>
* 650d76d - Periodic timer ticks (7 hours ago) <Antony Rheneus>
* 76f9556 - kernel binary in gzipped for uboot to extract (7 hours ago) <Antony Rheneus>
* 95367d7 - [ARMHF] kernel config reverted to address comment to add per change per commit (7 hours ago) <Antony Rheneus>
* d73c4cc - [kconfig] [ARMHF] [marvell armada cpu support] (7 hours ago) <Antony Rheneus>
* e6ff106 - remove unused sensor and sound card (7 hours ago) <Antony Rheneus>
* 0715da9 - no ntp external PPS needed (7 hours ago) <Antony Rheneus>
* e176474 - removed unused old 3com as limited memory is available to load kernel from uboot (7 hours ago) <Antony Rheneus>
* 2776504 - no qemu firmware needed (7 hours ago) <Antony Rheneus>
* 8579128 - EFI based firmware boot is not enabled in armarda a385 (7 hours ago) <Antony Rheneus>
* b477f3f - timer is set 100Hz for ticks in armada soc (7 hours ago) <Antony Rheneus>
* 77c818a - removed unused arch as limited memory is available to load kernel from uboot (7 hours ago) <Antony Rheneus>
* 812e1f4 - removed unused arch as limited memory is available to load kernel from uboot (7 hours ago) <Antony Rheneus>
* c46084b - MTD parts for flash partition layout (7 hours ago) <Antony Rheneus>
* 2156cb4 - peripheral drm quirks, usb support, ioport map (7 hours ago) <Antony Rheneus>
* 77a0273 - Enable gpio i2c mux, opte and sff eeprom module (7 hours ago) <Antony Rheneus>
* f715915 - timer set to 100Hz for armada soc (7 hours ago) <Antony Rheneus>
* deb1c60 - default gpio pins to 0, number of gpio pins will be based out from DTB as per platform config (7 hours ago) <Antony Rheneus>
* 5d5d609 - slab allocator is used and not SLUB as SLAB is well stable and tested for 32 bit arch (7 hours ago) <Antony Rheneus>
* 4605677 - Use well stabled regular slab allocator instead of SLUB (7 hours ago) <Antony Rheneus>
* 273a1ee - Disable heap randomization while calculating heap brk values to avoid any mem faults in 32 bit arch (7 hours ago) <Antony Rheneus>
* ffa2f97 - Use HZ_PERIODIC Periodic timer ticks and not dynamic ticks for armada soc (7 hours ago) <Antony Rheneus>
* da693fb - kernel binary in gzipped for uboot to extract (3 days ago) <Antony Rheneus>
* 6a727bd - [kconfig] [ARMHF] [marvell armada cpu support] (3 days ago) <Antony Rheneus>
* f4699e3 - Separate out SOC specific configuration based on platform architecture (3 days ago) <Antony Rheneus>
`

**Comment by antony-rheneus** [comment]
All the comments were addressed in PR https://github.com/Azure/sonic-linux-kernel/pull/176

**Pull request closed without merging**
