### PR TITLE
Kernel config changes to support cisco platforms

### PR DESCRIPTION
**Pull request by madhava28**
Kernel configuration is enabled to support device drivers
for sensor devices, gpio devices, MDIO mux devices,
ADC,DAC device and Intel SPI devies.

Signed-off-by: Madhava Reddy Siddareddygari <msiddare@cisco.com>

### CODE REVIEW

**Comment by sachinv-msft** [comment]
@saiarcot895 please help with your review on this pR

**Comment by saiarcot895** [comment]
Are all of these sensors/devices used on Cisco hardware? Is it possible to narrow down to devices that are actually needed here?

**Comment by madhava28** [comment]
> Are all of these sensors/devices used on Cisco hardware? Is it possible to narrow down to devices that are actually needed here?

Hi Saikrishna 
We are looking into optimizing the list. Will send an updated patch once ready

**Comment by saiarcot895** [comment]
Is it possible to add comments in `kconfig-inclusions` stating which platforms the drivers are enabled for?

**Comment by madhava28** [comment]
> Is it possible to add comments in `kconfig-inclusions` stating which platforms the drivers are enabled for?

kconfig-inclusion file updated to add comment for cisco platform supported

**Pull request merged**
