### PR TITLE
[Mellanox] Add patches for i2c API

### PR DESCRIPTION
**Pull request by volodymyrsamotiy**
From 6360f7272a370eee26118d46d963bb91ea36dfa2 Mon Sep 17 00:00:00 2001
From: Vadim Pasternak <vadimp@nvidia.com>
Date: Tue, 29 Sep 2020 08:58:57 +0300
Subject: [PATCH backport v4.19 0/8] 

Patchset contians backport of the below commits:
commit 3dcfe179570550c888ecfcd3d443d4de90a2d855
commit 3029a693beda5bff599feccc3beb9df1e141c786
commit 6a986993e43f176e07c28df560b1cfc3e9b80505
commit 95b75cbd1bc57ec5898517a3fb2f7621f16b26cd
commit f43d9d9b4eb869b1c1513ce8b931389b64b92db1
commit 27758c801663d17eafcd4e45179e7294a9c290b8

From commit 3dcfe179570550c888ecfcd3d443d4de90a2d855 backported only
setting of I2C bus frequnecy, other code from this commit has been
applied in older commits.
commit.

Patchset contians 'mlxsw: i2c: Add device info log', adding info log
to probe() routine to report firmware setting in 'dmesg'.
This is not upstream commit, but this code has been exist in Sonic from
day one and used for debug purpose.

Vadim Pasternak (7):
  mlxsw: i2c: Fix comment misspelling
  mlxsw: i2c: Modify input parameter name in initialization API
  mlxsw: i2c: Extend input parameters list of command API
  mlxsw: i2c: Extend initialization by querying resources data
  mlxsw: i2c: Extend initialization with querying firmware info
  mlxsw: i2c: Allow flexible setting of I2C transactions size
  mlxsw: core: Set different thermal polling time based on bus frequency capability

 drivers/net/ethernet/mellanox/mlxsw/core_thermal.c |   6 +-
 drivers/net/ethernet/mellanox/mlxsw/i2c.c          | 212 +++++++++++++++++----
 2 files changed, 178 insertions(+), 40 deletions(-)

-- 
2.11.0

### CODE REVIEW

**Comment by lguohan** [comment]
what is this commit id? 9bbd7efbc055b31b0e836936da94791c8890af4b

I cannot find in the https://github.com/torvalds/linux

**Comment by keboliu** [comment]
> what is this commit id? 9bbd7efbc055b31b0e836936da94791c8890af4b
> 
> I cannot find in the https://github.com/torvalds/linux

Hi @lguohan
as described in this PR description:

> Patchset contians 'mlxsw: i2c: Add device info log', adding info log
> to probe() routine to report firmware setting in 'dmesg'.
> This is not upstream commit, but this code has been exist in Sonic from
> day one and used for debug purposes.

this log is very useful for the issue debug, so we want to keep it although it's not in the upstream, of course, need your approval.

**Comment by liat-grozovik** [comment]
@volodymyrsamotiy lets please divide the patch to 2: 1 fully aligned to upstream code, 1 with the extra patch which is not upstream and for debug purposes.

**Comment by liat-grozovik** [comment]
@lguohan now it should be aligned to only upstream code. Please check

**Comment by liat-grozovik** [comment]
@lguohan kindly please check if this can be merged. we have broken image on master and this fix is a must.

**Comment by lguohan** [comment]
@liat-grozovik , i cannot find these commit id in the linux kernel tree.

Patchset contians backport of the below commits:
commit 3dcfe179570550c888ecfcd3d443d4de90a2d855
commit 3029a693beda5bff599feccc3beb9df1e141c786
commit 6a986993e43f176e07c28df560b1cfc3e9b80505
commit 95b75cbd1bc57ec5898517a3fb2f7621f16b26cd
commit f43d9d9b4eb869b1c1513ce8b931389b64b92db1
commit 27758c801663d17eafcd4e45179e7294a9c290b8

https://github.com/torvalds/linux/search?q=6360f7272a370eee26118d46d963bb91ea36dfa2

can you please help tell me where to find the upstream commit id?

**Comment by keboliu** [comment]
> @liat-grozovik , i cannot find these commit id in the linux kernel tree.
> 
> Patchset contians backport of the below commits:
> commit 3dcfe179570550c888ecfcd3d443d4de90a2d855
> commit 3029a693beda5bff599feccc3beb9df1e141c786
> commit 6a986993e43f176e07c28df560b1cfc3e9b80505
> commit 95b75cbd1bc57ec5898517a3fb2f7621f16b26cd
> commit f43d9d9b4eb869b1c1513ce8b931389b64b92db1
> commit 27758c801663d17eafcd4e45179e7294a9c290b8
> 
> https://github.com/torvalds/linux/search?q=3dcfe179570550c888ecfcd3d443d4de90a2d855
> 
> can you please help tell me where to find the upstream commit id?

@lguohan  I am not sure why the search is not working, but the commit hash is correct, I manually checked:

mlxsw: i2c: Fix comment misspelling     27758c801663d17eafcd4e45179e7294a9c290b8    https://github.com/torvalds/linux/commit/27758c801663d17eafcd4e45179e7294a9c290b8
mlxsw: i2c: Modify input parameter name in initialization API  f43d9d9b4eb869b1c1513ce8b931389b64b92db1  https://github.com/torvalds/linux/commit/f43d9d9b4eb869b1c1513ce8b931389b64b92db1
mlxsw: i2c: Extend input parameters list of command API    95b75cbd1bc57ec5898517a3fb2f7621f16b26cd  https://github.com/torvalds/linux/commit/95b75cbd1bc57ec5898517a3fb2f7621f16b26cd 
mlxsw: i2c: Extend initialization by querying resources data      6a986993e43f176e07c28df560b1cfc3e9b80505 https://github.com/torvalds/linux/commit/6a986993e43f176e07c28df560b1cfc3e9b80505
mlxsw: i2c: Extend initialization with querying firmware info     9bbd7efbc055b31b0e836936da94791c8890af4b  https://github.com/torvalds/linux/commit/9bbd7efbc055b31b0e836936da94791c8890af4b
mlxsw: i2c: Allow flexible setting of I2C transactions size        3029a693beda5bff599feccc3beb9df1e141c786   https://github.com/torvalds/linux/commit/3029a693beda5bff599feccc3beb9df1e141c786
mlxsw: core: Set different thermal polling time based on bus frequency capability    3dcfe179570550c888ecfcd3d443d4de90a2d855   https://github.com/torvalds/linux/commit/3dcfe179570550c888ecfcd3d443d4de90a2d855

**Comment by liat-grozovik** [comment]
@lguohan anything else is missing?

**Comment by lguohan** [comment]
@liat-grozovik , can you check this pr? after i merged the other one, it seems there is some patch issue on this.

**Comment by lguohan** [comment]
retest this please

**Pull request merged**
