### PR TITLE
fix bullseye build for arm64 and armhf

### PR DESCRIPTION
**Pull request by lguohan**
suggest to use rebase to merge to keep individual commits

### CODE REVIEW

**Comment by saiarcot895** [comment]
Is the original error message available? I'm curious why there's a build error for us on arm64, and the patch to fix the build error references upcoming changes to the networking headers.

**Comment by lguohan** [comment]
they are in the individual commit message.

**Comment by lguohan** [comment]
for arm64

Kernel support for 32-bit EL0 (COMPAT) [Y/n/?] y
  Enable kuser helpers page for 32-bit applications (KUSER_HELPERS) [Y/n/?] y
  Enable vDSO for 32-bit applications (COMPAT_VDSO) [Y/n/?] (NEW)

make -C olddefconfig will clear the this kconfig. thus, introduce
force_inclusion file and directly add the kconfig without further check.

**Review by saiarcot895 — APPROVED** [review]

**Pull request merged**
